apiVersion: v1
kind: ConfigMap
metadata:
  name: fcg-payment-api-config
  namespace: fcg-payment-ns
data:
  ASPNETCORE_URLS: "http://+:8080"
  ASPNETCORE_ENVIRONMENT: "Production"  
  SERVICEBUS_QUEUE: "compras-realizadas"
---
apiVersion: v1
kind: Secret
metadata:
  name: fcg-payment-api-secrets
  namespace: fcg-payment-ns
type: Opaque
data:  
  PAYMENT_CONNECTION_STRING: U2VydmVyPWZjZy1wb3N0Z3Jlcy5wb3N0Z3Jlcy5kYXRhYmFzZS5henVyZS5jb207RGF0YWJhc2U9ZmNnX3BheW1lbnRfZGI7UG9ydD01NDMyO1VzZXIgSWQ9ZmNnYWRtaW47UGFzc3dvcmQ9QmF0bWFuQDEyMzs=
  JWT_KEY: Y2hhdmUtc3VwZXItc2VjcmV0YS1wYXJhLWFzc2luYXItand0
  JWT_ISSUER: RmlhcC5GQ0c=
  JWT_AUDIENCE: RmlhcC5GQ0c=
  SERVICEBUS_CONNECTION: RW5kcG9pbnQ9c2I6Ly9mY2dmaWFwLXNlcnZpY2VidXMuc2VydmljZWJ1cy53aW5kb3dzLm5ldC87U2hhcmVkQWNjZXNzS2V5TmFtZT1Sb290TWFuYWdlU2hhcmVkQWNjZXNzS2V5O1NoYXJlZEFjY2Vzc0tleT1HdlhjMk5GREJOQWtPRVBvYlRibjJHLzIvWjFBWkFwTzYrQVNiTWI4NTFRPQ==
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fcg-payment-api
  namespace: fcg-payment-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fcg-payment-api
  template:
    metadata:
      labels:
        app: fcg-payment-api
    spec:
      containers:
        - name: fcg-payment-api
          image: fcgacr.azurecr.io/fiap-fcg-payment-api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: fcg-payment-api-config
          env:
            - name: PAYMENT_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: fcg-payment-api-secrets
                  key: PAYMENT_CONNECTION_STRING
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: fcg-payment-api-secrets
                  key: JWT_KEY
            - name: JWT_ISSUER
              valueFrom:
                secretKeyRef:
                  name: fcg-payment-api-secrets
                  key: JWT_ISSUER
            - name: JWT_AUDIENCE
              valueFrom:
                secretKeyRef:
                  name: fcg-payment-api-secrets
                  key: JWT_AUDIENCE           
            - name: SERVICEBUS_CONNECTION
              valueFrom:
                secretKeyRef:
                  name: fcg-payment-api-secrets
                  key: SERVICEBUS_CONNECTION
            - name: SERVICEBUS_QUEUE
              valueFrom:
                configMapKeyRef:
                  name: fcg-payment-api-config
                  key: SERVICEBUS_QUEUE
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "300m"
              memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: fcg-payment-api-svc
  namespace: fcg-payment-ns
spec:
  selector:
    app: fcg-payment-api
  ports:
    - name: http
      port: 80
      targetPort: 8080
  type: LoadBalancer
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: fcg-payment-api-hpa
  namespace: fcg-payment-ns
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: fcg-payment-api
  minReplicas: 1
  maxReplicas: 2
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
